### ISSUE TITLE
Why am I facing this issue?

### ISSUE THREAD

**Issue by MickeyVall** [backmeupplz/shieldy#92]
Hi there! I am hosting my bot Heroku with MongoDB Atlas and I get this error in every few hours:

`2020-07-23T15:55:19.218451+00:00 app[worker.1]:     at attachUser (/app/dist/middlewares/attachUser.js:13:5)
2020-07-23T15:55:19.218513+00:00 app[worker.1]: (node:53) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020-07-23T15:55:19.218643+00:00 app[worker.1]: (node:53) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-07-23T15:55:29.786442+00:00 app[worker.1]: checking candidates MongoTimeoutError: Server selection timed out after 10000 ms
2020-07-23T15:55:29.786457+00:00 app[worker.1]:     at Timeout._onTimeout (/app/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
2020-07-23T15:55:29.786458+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:549:17)
2020-07-23T15:55:29.786458+00:00 app[worker.1]:     at processTimers (internal/timers.js:492:7) {
2020-07-23T15:55:29.786460+00:00 app[worker.1]:   [Symbol(mongoErrorContextSymbol)]: {}
2020-07-23T15:55:29.786460+00:00 app[worker.1]: }
2020-07-23T15:55:29.786468+00:00 app[worker.1]: Finished checking chats with candidates
2020-07-23T15:55:34.582939+00:00 app[worker.1]: undefined MongoTimeoutError: Server selection timed out after 10000 ms
2020-07-23T15:55:34.582955+00:00 app[worker.1]:     at Timeout._onTimeout (/app/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
2020-07-23T15:55:34.582957+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:549:17)
2020-07-23T15:55:34.582957+00:00 app[worker.1]:     at processTimers (internal/timers.js:492:7) {
2020-07-23T15:55:34.582958+00:00 app[worker.1]:   [Symbol(mongoErrorContextSymbol)]: {}
2020-07-23T15:55:34.582958+00:00 app[worker.1]: }
2020-07-23T15:55:34.583307+00:00 app[worker.1]: (node:53) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'restrict' of undefined
2020-07-23T15:55:34.583307+00:00 app[worker.1]:     at checkRestrict (/app/dist/middlewares/checkRestrict.js:10:21)
2020-07-23T15:55:34.583308+00:00 app[worker.1]:     at execute (/app/node_modules/telegraf/composer.js:370:13)
2020-07-23T15:55:34.583308+00:00 app[worker.1]:     at /app/node_modules/telegraf/composer.js:370:49
2020-07-23T15:55:34.583308+00:00 app[worker.1]:     at execute (/app/node_modules/telegraf/composer.js:370:13)
2020-07-23T15:55:34.583309+00:00 app[worker.1]:     at /app/node_modules/telegraf/composer.js:370:49
2020-07-23T15:55:34.583309+00:00 app[worker.1]:     at attachUser (/app/dist/middlewares/attachUser.js:13:5)
2020-07-23T15:55:34.583355+00:00 app[worker.1]: (node:53) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2020-07-23T15:55:44.788828+00:00 app[worker.1]: checking candidates MongoTimeoutError: Server selection timed out after 10000 ms
2020-07-23T15:55:44.788841+00:00 app[worker.1]:     at Timeout._onTimeout (/app/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
2020-07-23T15:55:44.788841+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:549:17)
2020-07-23T15:55:44.788842+00:00 app[worker.1]:     at processTimers (internal/timers.js:492:7) {
2020-07-23T15:55:44.788843+00:00 app[worker.1]:   [Symbol(mongoErrorContextSymbol)]: {}
2020-07-23T15:55:44.788844+00:00 app[worker.1]: }
2020-07-23T15:55:44.788850+00:00 app[worker.1]: Finished checking chats with candidates
2020-07-23T15:55:59.789349+00:00 app[worker.1]: checking candidates MongoTimeoutError: Server selection timed out after 10000 ms
2020-07-23T15:55:59.789394+00:00 app[worker.1]:     at Timeout._onTimeout (/app/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
2020-07-23T15:55:59.789395+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:549:17)
2020-07-23T15:55:59.789395+00:00 app[worker.1]:     at processTimers (internal/timers.js:492:7) {
2020-07-23T15:55:59.789396+00:00 app[worker.1]:   [Symbol(mongoErrorContextSymbol)]: {}
2020-07-23T15:55:59.789396+00:00 app[worker.1]: }
2020-07-23T15:55:59.789404+00:00 app[worker.1]: Finished checking chats with candidates
2020-07-23T15:56:01.365696+00:00 app[worker.1]: undefined MongoTimeoutError: Server selection timed out after 10000 ms
2020-07-23T15:56:01.365716+00:00 app[worker.1]:     at Timeout._onTimeout (/app/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
2020-07-23T15:56:01.365716+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:549:17)
2020-07-23T15:56:01.365717+00:00 app[worker.1]:     at processTimers (internal/timers.js:492:7) {
2020-07-23T15:56:01.365718+00:00 app[worker.1]:   [Symbol(mongoErrorContextSymbol)]: {}
2020-07-23T15:56:01.365718+00:00 app[worker.1]: }
2020-07-23T15:56:01.366111+00:00 app[worker.1]: (node:53) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'restrict' of undefined
2020-07-23T15:56:01.366111+00:00 app[worker.1]:     at checkRestrict (/app/dist/middlewares/checkRestrict.js:10:21)
2020-07-23T15:56:01.366112+00:00 app[worker.1]:     at execute (/app/node_modules/telegraf/composer.js:370:13)
2020-07-23T15:56:01.366112+00:00 app[worker.1]:     at /app/node_modules/telegraf/composer.js:370:49
2020-07-23T15:56:01.366112+00:00 app[worker.1]:     at execute (/app/node_modules/telegraf/composer.js:370:13)
2020-07-23T15:56:01.366112+00:00 app[worker.1]:     at /app/node_modules/telegraf/composer.js:370:49
2020-07-23T15:56:01.366113+00:00 app[worker.1]:     at attachUser (/app/dist/middlewares/attachUser.js:13:5)
2020-07-23T15:56:01.366184+00:00 app[worker.1]: (node:53) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
2020-07-23T15:56:01.674274+00:00 app[worker.1]: undefined MongoTimeoutError: Server selection timed out after 10000 ms
2020-07-23T15:56:01.674289+00:00 app[worker.1]:     at Timeout._onTimeout (/app/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
2020-07-23T15:56:01.674290+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:549:17)
2020-07-23T15:56:01.674291+00:00 app[worker.1]:     at processTimers (internal/timers.js:492:7) {
2020-07-23T15:56:01.674291+00:00 app[worker.1]:   [Symbol(mongoErrorContextSymbol)]: {}
2020-07-23T15:56:01.674292+00:00 app[worker.1]: }
2020-07-23T15:56:01.675428+00:00 app[worker.1]: (node:53) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'restrict' of undefined
2020-07-23T15:56:01.675428+00:00 app[worker.1]:     at checkRestrict (/app/dist/middlewares/checkRestrict.js:10:21)
2020-07-23T15:56:01.675428+00:00 app[worker.1]:     at execute (/app/node_modules/telegraf/composer.js:370:13)
2020-07-23T15:56:01.675429+00:00 app[worker.1]:     at /app/node_modules/telegraf/composer.js:370:49
2020-07-23T15:56:01.675429+00:00 app[worker.1]:     at execute (/app/node_modules/telegraf/composer.js:370:13)
2020-07-23T15:56:01.675429+00:00 app[worker.1]:     at /app/node_modules/telegraf/composer.js:370:49
2020-07-23T15:56:01.675430+00:00 app[worker.1]:     at attachUser (/app/dist/middlewares/attachUser.js:13:5)
2020-07-23T15:56:01.675471+00:00 app[worker.1]: (node:53) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
2020-07-23T15:56:01.826370+00:00 app[worker.1]: undefined MongoTimeoutError: Server selection timed out after 10000 ms
2020-07-23T15:56:01.826372+00:00 app[worker.1]:     at Timeout._onTimeout (/app/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
2020-07-23T15:56:01.826373+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:549:17)
2020-07-23T15:56:01.826373+00:00 app[worker.1]:     at processTimers (internal/timers.js:492:7) {
2020-07-23T15:56:01.826374+00:00 app[worker.1]:   [Symbol(mongoErrorContextSymbol)]: {}
2020-07-23T15:56:01.826374+00:00 app[worker.1]: }
2020-07-23T15:56:01.826835+00:00 app[worker.1]: (node:53) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'restrict' of undefined
2020-07-23T15:56:01.826836+00:00 app[worker.1]:     at checkRestrict (/app/dist/middlewares/checkRestrict.js:10:21)
2020-07-23T15:56:01.826837+00:00 app[worker.1]:     at execute (/app/node_modules/telegraf/composer.js:370:13)
2020-07-23T15:56:01.826837+00:00 app[worker.1]:     at /app/node_modules/telegraf/composer.js:370:49
2020-07-23T15:56:01.826838+00:00 app[worker.1]:     at execute (/app/node_modules/telegraf/composer.js:370:13)
2020-07-23T15:56:01.826838+00:00 app[worker.1]:     at /app/node_modules/telegraf/composer.js:370:49
2020-07-23T15:56:01.826838+00:00 app[worker.1]:     at attachUser (/app/dist/middlewares/attachUser.js:13:5)
2020-07-23T15:56:01.826892+00:00 app[worker.1]: (node:53) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
2020-07-23T15:56:02.027694+00:00 app[worker.1]: undefined MongoTimeoutError: Server selection timed out after 10000 ms
2020-07-23T15:56:02.027712+00:00 app[worker.1]:     at Timeout._onTimeout (/app/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
2020-07-23T15:56:02.027713+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:549:17)
2020-07-23T15:56:02.027713+00:00 app[worker.1]:     at processTimers (internal/timers.js:492:7) {
2020-07-23T15:56:02.027714+00:00 app[worker.1]:   [Symbol(mongoErrorContextSymbol)]: {}
2020-07-23T15:56:02.027715+00:00 app[worker.1]: }
2020-07-23T15:56:02.028074+00:00 app[worker.1]: (node:53) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'restrict' of undefined
2020-07-23T15:56:02.028075+00:00 app[worker.1]:     at checkRestrict (/app/dist/middlewares/checkRestrict.js:10:21)
2020-07-23T15:56:02.028075+00:00 app[worker.1]:     at execute (/app/node_modules/telegraf/composer.js:370:13)
2020-07-23T15:56:02.028076+00:00 app[worker.1]:     at /app/node_modules/telegraf/composer.js:370:49
2020-07-23T15:56:02.028076+00:00 app[worker.1]:     at execute (/app/node_modules/telegraf/composer.js:370:13)
2020-07-23T15:56:02.028077+00:00 app[worker.1]:     at /app/node_modules/telegraf/composer.js:370:49
2020-07-23T15:56:02.028077+00:00 app[worker.1]:     at attachUser (/app/dist/middlewares/attachUser.js:13:5)
2020-07-23T15:56:02.028115+00:00 app[worker.1]: (node:53) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
2020-07-23T15:56:14.797496+00:00 app[worker.1]: checking candidates MongoTimeoutError: Server selection timed out after 10000 ms
2020-07-23T15:56:14.797510+00:00 app[worker.1]:     at Timeout._onTimeout (/app/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
2020-07-23T15:56:14.797511+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:549:17)
2020-07-23T15:56:14.797512+00:00 app[worker.1]:     at processTimers (internal/timers.js:492:7) {
2020-07-23T15:56:14.797512+00:00 app[worker.1]:   [Symbol(mongoErrorContextSymbol)]: {}
2020-07-23T15:56:14.797513+00:00 app[worker.1]: }
2020-07-23T15:56:14.797522+00:00 app[worker.1]: Finished checking chats with candidates
2020-07-23T15:56:29.796776+00:00 app[worker.1]: checking candidates MongoTimeoutError: Server selection timed out after 10000 ms
2020-07-23T15:56:29.796787+00:00 app[worker.1]:     at Timeout._onTimeout (/app/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
2020-07-23T15:56:29.796788+00:00 app[worker.1]:     at listOnTimeout (internal/timers.js:549:17)
2020-07-23T15:56:29.796788+00:00 app[worker.1]:     at processTimers (internal/timers.js:492:7) {
2020-07-23T15:56:29.796789+00:00 app[worker.1]:   [Symbol(mongoErrorContextSymbol)]: {}
2020-07-23T15:56:29.796789+00:00 app[worker.1]: }
2020-07-23T15:56:29.796801+00:00 app[worker.1]: Finished checking chats with candidates`

**Comment by backmeupplz** [comment]
Sorry, I don't know.
